# Generated by Django 4.0.10 on 2024-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='album_name',
            field=models.CharField(default='Unknown Album', max_length=100),
        ),
    ]
